owner: SimronJ
repo: Houser-Uptime

sites:
  # ==== USER & AUTH ====
  - name: Prod - GET /user-roles
    url: https://api.thehouserapp.com/user-roles
  - name: Staging - GET /user-roles
    url: http://54.162.155.98:3001/user-roles

  - name: Prod - GET /user-subscription
    url: https://api.thehouserapp.com/user-subscription
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404, 405]
  - name: Staging - GET /user-subscription
    url: http://54.162.155.98:3001/user-subscription
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404, 405]

  - name: Prod - GET /user-subscription-history
    url: https://api.thehouserapp.com/user-subscription-history
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404, 405]
  - name: Staging - GET /user-subscription-history
    url: http://54.162.155.98:3001/user-subscription-history
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404, 405]

  - name: Prod - GET /user-profile
    url: https://api.thehouserapp.com/user-profile
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404, 405]
  - name: Staging - GET /user-profile
    url: http://54.162.155.98:3001/user-profile
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404, 405]

  - name: Prod - GET /clients
    url: https://api.thehouserapp.com/clients
  - name: Staging - GET /clients
    url: http://54.162.155.98:3001/clients

  - name: Prod - GET /user/1
    url: https://api.thehouserapp.com/user/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /user/1
    url: http://54.162.155.98:3001/user/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  # ==== PROPERTIES ====
  - name: Prod - GET /getAllProperties
    url: https://api.thehouserapp.com/getAllProperties?minLatitude=33.0000&minLongitude=-97.0000&maxLatitude=33.0100&maxLongitude=-96.9900&pageSize=1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
    maxResponseTime: 15000
  - name: Staging - GET /getAllProperties
    url: http://54.162.155.98:3001/getAllProperties?minLatitude=33.0000&minLongitude=-97.0000&maxLatitude=33.0100&maxLongitude=-96.9900&pageSize=1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
    maxResponseTime: 15000

  - name: Prod - GET /PlanpoProperties
    url: https://api.thehouserapp.com/PlanpoProperties
  - name: Staging - GET /PlanpoProperties
    url: http://54.162.155.98:3001/PlanpoProperties

  - name: Prod - GET /getAllPropertiesCoordinates
    url: https://api.thehouserapp.com/getAllPropertiesCoordinates
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /getAllPropertiesCoordinates
    url: http://54.162.155.98:3001/getAllPropertiesCoordinates
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /properties/by-polygon
    url: https://api.thehouserapp.com/properties/by-polygon
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /properties/by-polygon
    url: http://54.162.155.98:3001/properties/by-polygon
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /propertyById/1
    url: https://api.thehouserapp.com/propertyById/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /propertyById/1
    url: http://54.162.155.98:3001/propertyById/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  - name: Prod - GET /property/1
    url: https://api.thehouserapp.com/property/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /property/1
    url: http://54.162.155.98:3001/property/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  - name: Prod - GET /getPropertiesByAddress
    url: https://api.thehouserapp.com/getPropertiesByAddress?address=123%20Main%20St
    expectedStatusCodes: [200, 201, 204, 400, 404]
  - name: Staging - GET /getPropertiesByAddress
    url: http://54.162.155.98:3001/getPropertiesByAddress?address=123%20Main%20St
    expectedStatusCodes: [200, 201, 204, 400, 404]

  - name: Prod - GET /properties/filterByCityAndZip
    url: https://api.thehouserapp.com/properties/filterByCityAndZip?city=Plano
    expectedStatusCodes: [200, 201, 204, 400, 404]
    maxResponseTime: 15000
  - name: Staging - GET /properties/filterByCityAndZip
    url: http://54.162.155.98:3001/properties/filterByCityAndZip?city=Plano
    expectedStatusCodes: [200, 201, 204, 400, 404]
    maxResponseTime: 15000

  - name: Prod - GET /properties/basicFilters
    url: https://api.thehouserapp.com/properties/basicFilters
  - name: Staging - GET /properties/basicFilters
    url: http://54.162.155.98:3001/properties/basicFilters

  - name: Prod - GET /properties/cashflow/1
    url: https://api.thehouserapp.com/properties/cashflow/1
    expectedStatusCodes: [200, 201, 204, 400, 404]
  - name: Staging - GET /properties/cashflow/1
    url: http://54.162.155.98:3001/properties/cashflow/1
    expectedStatusCodes: [200, 201, 204, 400, 404]

  - name: Prod - GET /properties/firstTimeHomeBuyer/1
    url: https://api.thehouserapp.com/properties/firstTimeHomeBuyer/1
    expectedStatusCodes: [200, 201, 204, 400, 404]
  - name: Staging - GET /properties/firstTimeHomeBuyer/1
    url: http://54.162.155.98:3001/properties/firstTimeHomeBuyer/1
    expectedStatusCodes: [200, 201, 204, 400, 404]

  - name: Prod - GET /properties/fixAndFlip/1
    url: https://api.thehouserapp.com/properties/fixAndFlip/1
    expectedStatusCodes: [200, 201, 204, 400, 404]
  - name: Staging - GET /properties/fixAndFlip/1
    url: http://54.162.155.98:3001/properties/fixAndFlip/1
    expectedStatusCodes: [200, 201, 204, 400, 404]

  - name: Prod - GET /properties/house-hack/1
    url: https://api.thehouserapp.com/properties/house-hack/1
    expectedStatusCodes: [200, 201, 204, 400, 404]
  - name: Staging - GET /properties/house-hack/1
    url: http://54.162.155.98:3001/properties/house-hack/1
    expectedStatusCodes: [200, 201, 204, 400, 404]

  # ==== PROPERTY QUESTIONNAIRES ====
  - name: Prod - GET /property-questionnaires
    url: https://api.thehouserapp.com/property-questionnaires
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /property-questionnaires
    url: http://54.162.155.98:3001/property-questionnaires
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /property-questionnaires/1
    url: https://api.thehouserapp.com/property-questionnaires/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /property-questionnaires/1
    url: http://54.162.155.98:3001/property-questionnaires/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  - name: Prod - GET /property-questionnaires/prefilled/1
    url: https://api.thehouserapp.com/property-questionnaires/prefilled/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /property-questionnaires/prefilled/1
    url: http://54.162.155.98:3001/property-questionnaires/prefilled/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  # ==== ONBOARDING QUESTIONNAIRE ====
  - name: Prod - GET /questionnaire
    url: https://api.thehouserapp.com/questionnaire
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /questionnaire
    url: http://54.162.155.98:3001/questionnaire
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /questions
    url: https://api.thehouserapp.com/questions
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /questions
    url: http://54.162.155.98:3001/questions
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  # ==== USER LIKED PROPERTIES ====
  - name: Prod - GET /user-likes
    url: https://api.thehouserapp.com/user-likes
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /user-likes
    url: http://54.162.155.98:3001/user-likes
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  # ==== BUY HOUSE / BUY PROPERTY ====
  - name: Prod - GET /buy-house
    url: https://api.thehouserapp.com/buy-house
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /buy-house
    url: http://54.162.155.98:3001/buy-house
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /buy-property
    url: https://api.thehouserapp.com/buy-property
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /buy-property
    url: http://54.162.155.98:3001/buy-property
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /buy-property/1
    url: https://api.thehouserapp.com/buy-property/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /buy-property/1
    url: http://54.162.155.98:3001/buy-property/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  # ==== SHOWINGS ====
  - name: Prod - GET /showings
    url: https://api.thehouserapp.com/showings
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]
  - name: Staging - GET /showings
    url: http://54.162.155.98:3001/showings
    expectedStatusCodes: [200, 201, 204, 400, 401, 403]

  - name: Prod - GET /showings/1
    url: https://api.thehouserapp.com/showings/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]
  - name: Staging - GET /showings/1
    url: http://54.162.155.98:3001/showings/1
    expectedStatusCodes: [200, 201, 204, 400, 401, 403, 404]

  # ==== AI / AUDIO ====
  - name: Prod - GET /signedaudio
    url: https://api.thehouserapp.com/signedaudio
    expectedStatusCodes: [200, 201, 204, 400, 404]
  - name: Staging - GET /signedaudio
    url: http://54.162.155.98:3001/signedaudio
    expectedStatusCodes: [200, 201, 204, 400, 404]

  # ==== STRIPE / BILLING ====
  - name: Prod - GET /subscription-plans
    url: https://api.thehouserapp.com/subscription-plans
    expectedStatusCodes: [200, 201, 204, 400, 401]
  - name: Staging - GET /subscription-plans
    url: http://54.162.155.98:3001/subscription-plans
    expectedStatusCodes: [200, 201, 204, 400, 401]

  - name: Prod - GET /1/paymentMethods
    url: https://api.thehouserapp.com/1/paymentMethods
    expectedStatusCodes: [200, 201, 204, 400, 401, 404]
  - name: Staging - GET /1/paymentMethods
    url: http://54.162.155.98:3001/1/paymentMethods
    expectedStatusCodes: [200, 201, 204, 400, 401, 404]

  - name: Prod - GET /1/customer/session
    url: https://api.thehouserapp.com/1/customer/session
    expectedStatusCodes: [200, 201, 204, 400, 401, 404]
  - name: Staging - GET /1/customer/session
    url: http://54.162.155.98:3001/1/customer/session
    expectedStatusCodes: [200, 201, 204, 400, 401, 404]

  - name: Prod - GET /1/customer/subscriptions
    url: https://api.thehouserapp.com/1/customer/subscriptions
    expectedStatusCodes: [200, 201, 204, 400, 401, 404]
  - name: Staging - GET /1/customer/subscriptions
    url: http://54.162.155.98:3001/1/customer/subscriptions
    expectedStatusCodes: [200, 201, 204, 400, 401, 404]

  # ==== QUERIES ====
  - name: Prod - GET /getQueries
    url: https://api.thehouserapp.com/getQueries
  - name: Staging - GET /getQueries
    url: http://54.162.155.98:3001/getQueries

workflowSchedule:
  uptime: "*/10 * * * *"

status-website:
  baseUrl: /Houser-Uptime
  name: Houser API Status
  
  # Add these for better branding:
  logoUrl: https://yourcompany.com/logo.png  # Optional: your company logo
  introTitle: "**Houser App** System Status"
  introMessage: "Real-time monitoring of our production and staging APIs"
  
  # Add navigation links:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Support
      href: https://support.thehouserapp.com  # Your support page
    
  # Optional: Custom theme
  theme: dark  # or "light"